export type LocalizedNamesDto = {
	"ar-AE": string;
	"de-DE": string;
	"en-GB": string;
	"en-US": string;
	"es-ES": string;
	"es-MX": string;
	"fr-FR": string;
	"id-ID": string;
	"it-IT": string;
	"ja-JP": string;
	"ko-KR": string;
	"pl-PL": string;
	"pt-BR": string;
	"ru-RU": string;
	"th-TH": string;
	"tr-TR": string;
	"vi-VN": string;
	"zh-CN": string;
	"zh-TW": string;
};
