name: wrapper-valorant

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: action/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/@LordPrinz
          scope: '@LordPrinz'
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOEKN: ${{secrets.GITHUB_TOKEN}}
